<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Elastic.CommonSchema.Serilog" Version="9.0.0" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.5" />
		<PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
		<PackageReference Include="Serilog.Exceptions" Version="8.4.0" />
		<PackageReference Include="Serilog.Expressions" Version="5.1.0-dev-00186" />
		<PackageReference Include="Serilog.Formatting.Elasticsearch" Version="10.0.0" />
		<PackageReference Include="Serilog.Settings.AppSettings" Version="3.0.0" />
		<PackageReference Include="Serilog.Sinks.Async" Version="2.1.0" />
		<PackageReference Include="System.CommandLine" Version="2.0.0-beta4.22272.1" />
		<PackageReference Include="System.CommandLine.NamingConventionBinder" Version="2.0.0-beta4.22272.1" />
		<PackageReference Include="System.Text.Json" Version="10.0.5" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Saltworks.SaltMiner.Core\Saltworks.SaltMiner.Core\Saltworks.SaltMiner.Core.csproj" />
	</ItemGroup>

</Project>
