FROM mcr.microsoft.com/dotnet/aspnet:8.0.20-alpine3.22-amd64

LABEL base-image="mcr.microsoft.com/dotnet/aspnet:8.0.20-alpine3.22-amd64"
LABEL vendor="Saltworks Security, LLC"

ENV APP_ROOT=/opt/saltworks/saltminer
WORKDIR ${APP_ROOT}/app/ui-api

ARG ARTIFACT_PATH=.
ENV ARTIFACT_PATH=$ARTIFACT_PATH
ARG DEPLOY_PATH=invalid
ENV DEPLOY_PATH=$DEPLOY_PATH
COPY $ARTIFACT_PATH .

ENV DOTNET_PRINT_TELEMETRY_MESSAGE=false
ENV SALTMINER_CONFIG_PATH=${APP_ROOT}/config/ui-api/

# curl is used for healthcheck.
RUN apk add --no-cache curl

EXPOSE 5001

COPY $DEPLOY_PATH/entrypoint-ui-api.sh ${APP_ROOT}/entrypoint.sh
RUN chmod +x ${APP_ROOT}/entrypoint.sh

ENTRYPOINT ${APP_ROOT}/entrypoint.sh

