FROM mcr.microsoft.com/dotnet/aspnet:8.0.20-alpine3.22-amd64

LABEL base-image="mcr.microsoft.com/dotnet/aspnet:8.0.20-alpine3.22-amd64"
LABEL vendor="Saltworks Security, LLC"

ARG ARTIFACT_PATH=.
ARG DATASTORE_SEED_PATH=./invalid-index-templates-path

ENV APP_ROOT=/opt/saltworks/saltminer
ENV ARTIFACT_PATH=$ARTIFACT_PATH
ENV DATASTORE_SEED_PATH=$DATASTORE_SEED_PATH
ENV DOTNET_PRINT_TELEMETRY_MESSAGE=false
ENV SALTMINER_CONFIG_PATH=${APP_ROOT}/config/api
ENV USER=saltminer
ENV GROUPNAME=$USER
ENV UID=10000
ENV GID=10001

WORKDIR ${APP_ROOT}/app/api

COPY $ARTIFACT_PATH ./
COPY $DATASTORE_SEED_PATH/* ./default-datastore-seed/

# curl is used for healthcheck.
RUN apk add --no-cache curl \
  && mkdir -p ${APP_ROOT}/config/api \
  && mkdir -p ${APP_ROOT}/logs \
  && addgroup \
    --gid "$GID" \
    "$GROUPNAME" \
  && adduser \
    --disabled-password \
    --gecos "" \
    --home "$(pwd)" \
    --ingroup "$GROUPNAME" \
    --no-create-home \
    --uid "$UID" \
    $USER \
  && chown -R $USER:$GROUPNAME . \
  && chown -R $USER:$GROUPNAME ${APP_ROOT}/config \
  && chown -R $USER:$GROUPNAME ${APP_ROOT}/logs

EXPOSE 5000

USER $USER

ENTRYPOINT ["/usr/bin/dotnet", "/opt/saltworks/saltminer/app/api/Saltworks.SaltMiner.DataApi.dll"]
