FROM mcr.microsoft.com/dotnet/aspnet:8.0.20-alpine3.22-amd64

LABEL base-image="mcr.microsoft.com/dotnet/aspnet:8.0.20-alpine3.22-amd64"
LABEL vendor="Saltworks Security, LLC"

ARG ARTIFACT_PATH=.
ARG DATASTORE_SEED_PATH=./invalid-index-templates-path

ENV APP_ROOT=/opt/saltworks/saltminer
ENV ARTIFACT_PATH=$ARTIFACT_PATH
ENV DATASTORE_SEED_PATH=$DATASTORE_SEED_PATH
ENV DOTNET_PRINT_TELEMETRY_MESSAGE=false
ENV SALTMINER_CONFIG_PATH=${APP_ROOT}/config/api

WORKDIR ${APP_ROOT}/app/api

COPY $ARTIFACT_PATH ./

# curl is used for healthcheck.
# jq is used for configuration file manipulation
# RUN apk add --no-cache curl jq bash \
#   && mkdir -p ${APP_ROOT}/config/api \
#   && mkdir -p ${APP_ROOT}/logs \
#   && chmod u+x config-api.sh \
#   && mv ${APP_ROOT}/app/api/appsettings.json ${APP_ROOT}/config/api/
RUN mkdir -p ${APP_ROOT}/logs
COPY $DATASTORE_SEED_PATH/* ./default-datastore-seed/

EXPOSE 5000

ENTRYPOINT ["/usr/bin/dotnet", "${smapp}/Saltworks.SaltMiner.DataApi.dll"]