FROM mcr.microsoft.com/dotnet/aspnet:8.0.20-alpine3.22-amd64

LABEL base-image="mcr.microsoft.com/dotnet/aspnet:8.0.20-alpine3.22-amd64"
LABEL vendor="Saltworks Security, LLC"

# default invalid values, we expect to be overridden with build args
ARG ARTIFACT_PATH=invalid
ARG MGR_ARTIFACT_PATH=invalid
ARG AGENT_ARTIFACT_PATH=invalid
ARG PY_ARTIFACT_PATH=invalid
ARG DEPLOY_PATH=invalid

ENV APP_ROOT=/opt/saltworks/saltminer
ENV ARTIFACT_PATH=$ARTIFACT_PATH
ENV MGR_ARTIFACT_PATH=$MGR_ARTIFACT_PATH
ENV AGENT_ARTIFACT_PATH=$AGENT_ARTIFACT_PATH
ENV PY_ARTIFACT_PATH=$PY_ARTIFACT_PATH
ENV DEPLOY_PATH=$DEPLOY_PATH

WORKDIR ${APP_ROOT}/app

RUN mkdir -p ${APP_ROOT}/config \
  && mkdir -p ${APP_ROOT}/logs \
  && apk add --no-cache py3-pip bash

COPY $AGENT_ARTIFACT_PATH ./agent/
COPY $MGR_ARTIFACT_PATH ./manager/
COPY $ARTIFACT_PATH ./servicemanager/
COPY $PY_ARTIFACT_PATH ./python/
COPY $DEPLOY_PATH/scripts ./default-scripts
RUN chmod +x ./default-scripts/*.sh

RUN mkdir -p ./python/Defaults/ && \
    for dir in Config Custom AppVulsCustom Mappings AuthHelperCustom; do \
      mv ./python/$dir ./python/Defaults/$dir; \
    done && \
    pip install -r ./python/requirements.txt --break-system-packages

ENV DOTNET_PRINT_TELEMETRY_MESSAGE=false
ENV SALTMINER_CONFIG_PATH=${APP_ROOT}/config

COPY $DEPLOY_PATH/entrypoint-services.sh ${APP_ROOT}/entrypoint.sh
RUN chmod +x ${APP_ROOT}/entrypoint.sh

ENTRYPOINT ${APP_ROOT}/entrypoint.sh
