FROM mcr.microsoft.com/dotnet/aspnet:8.0.20-alpine3.22-amd64

LABEL base-image="mcr.microsoft.com/dotnet/aspnet:8.0.20-alpine3.22-amd64"
LABEL vendor="Saltworks Security, LLC"

# default invalid values, we expect to be overridden with build args
ARG ARTIFACT_PATH=invalid
ARG MGR_ARTIFACT_PATH=invalid
ARG AGENT_ARTIFACT_PATH=invalid
ARG PY_ARTIFACT_PATH=invalid
ARG JOB_ARTIFACT_PATH=invalid

ENV APP_ROOT=/opt/saltworks/saltminer
ENV ARTIFACT_PATH=$ARTIFACT_PATH
ENV MGR_ARTIFACT_PATH=$MGR_ARTIFACT_PATH
ENV AGENT_ARTIFACT_PATH=$AGENT_ARTIFACT_PATH
ENV PY_ARTIFACT_PATH=$PY_ARTIFACT_PATH
ENV JOB_ARTIFACT_PATH=$JOB_ARTIFACT_PATH
ENV DOTNET_PRINT_TELEMETRY_MESSAGE=false
ENV SALTMINER_CONFIG_PATH=${APP_ROOT}/config
ENV USER=saltminer
ENV GROUPNAME=$USER
ENV UID=10000
ENV GID=10001

WORKDIR ${APP_ROOT}/app

RUN mkdir -p ${APP_ROOT}/config \
  && mkdir -p ${APP_ROOT}/logs \
  && apk add --no-cache py3-pip

COPY $AGENT_ARTIFACT_PATH ./agent/
COPY $MGR_ARTIFACT_PATH ./manager/
COPY $ARTIFACT_PATH ./servicemanager/
COPY $PY_ARTIFACT_PATH ./python/

RUN mkdir -p ./python/Defaults/ && \
    ls ./python && \
    for dir in Config Custom AppVulsCustom AuthHelperCustom; do \
      mv ./python/$dir ./python/Defaults/$dir; \
    done && \
    mkdir -p ./python/Mappings/ && \
    pip install -r ./python/requirements.txt --break-system-packages && \
    addgroup \
      --gid "$GID" \
      "$GROUPNAME" && \
    adduser \
      --disabled-password \
      --gecos "" \
      --home "$(pwd)" \
      --ingroup "$GROUPNAME" \
      --no-create-home \
      --uid "$UID" \
      $USER && \
    chown -R $USER:$GROUPNAME . && \
    chown -R $USER:$GROUPNAME ${APP_ROOT}/config && \
    chown -R $USER:$GROUPNAME ${APP_ROOT}/logs

USER $USER

ENTRYPOINT ["/usr/bin/dotnet", "/opt/saltworks/saltminer/app/servicemanager/Saltworks.SaltMiner.ServiceManager.dll"]
