# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Saltworks.SaltMiner.Ui.Api

on:
  push:
    branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]
    paths:
    - 'Saltworks.SaltMiner.Ui.Api/**'
    - '.github/workflows/saltworks-saltminer-ui-api.yml'

jobs:
  build_uiapi:
    name: Build Saltworks.SaltMiner.Ui.Api

    runs-on:
    - self-hosted
    - dotnet
    defaults:
      run:
        working-directory: ./Saltworks.SaltMiner.Ui.Api/Saltworks.SaltMiner.Ui.Api

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Use artifacts directory
      run: dotnet new buildprops --use-artifacts
    - name: Restore dependencies
      run: dotnet restore --disable-build-servers
    - name: Build
      run: dotnet build --no-restore

    - name: Login to the container registry
      uses: docker/login-action@v3.4.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: saltworks/saltminer
        tags: |
          type=raw,value=ui-api-${{ github.ref_name }}.{{date 'YYYYMMDD-HHmmss'}}
        labels: |
          org.opencontainers.image.title=saltminer-jobmanager
          org.opencontainers.image.description=SaltMiner UI API
          org.opencontainers.image.vendor=Saltworks Security, LLC
          org.opencontainers.image.created={{date 'YYYY-MM-DDTHH:mm:ss.SSS[Z]'}}
    #- name: Test
    #  run: dotnet test --no-build --verbosity normal
