name: Saltworks.SaltMiner.Services

on:
  push:
    branches:
    - main
    - '3.*'
    paths:
    - 'Saltworks.SaltMiner.Manager/**'
    - 'Saltworks.SaltMiner.Python/**'
    - 'Saltworks.SaltMiner.ServiceManager/**'
    - 'Saltworks.SaltMiner.SyncAgent/**'
    - 'Saltworks.SaltMiner.SourceAdapters.Core/**'
    - 'Saltworks.SaltMiner.SourceAdapters/**'
    - 'Saltworks.SaltMiner.ConfigurationWizard/**'
    - 'Saltworks.SaltMiner.ConsoleApp.Core/**'
    - 'Saltworks.SaltMiner.Core/**'
    - 'Saltworks.Common.Data/**'
    - 'Saltworks.SaltMiner.DataClient/**'
    - 'Saltworks.Utility.ApiHelper/**'
    - 'Saltworks.SaltMiner.Licensing.Core/**'
    - '.github/workflows/saltworks-saltminer-services.yml'
    - '.dockerfiles/Dockerfile-services'
  workflow_dispatch:
    inputs:
      push_to_docker_hub:
        description: 'Push to Docker Hub'
        required: false
        default: false
        type: boolean
      diagnostic_mode:
        description: 'Enable diagnostic output'
        required: false
        default: false
        type: boolean

permissions:
  packages: write
  contents: read

jobs:
  build_services:
    name: Build Services
    runs-on:
    - self-hosted
    - dotnet
    defaults:
      run:
        working-directory: ./Saltworks.SaltMiner.ServiceManager/Saltworks.SaltMiner.ServiceManager
    env:
      CONFIGURATION: release
      CONFIG_FILE: ServiceManagerSettings.json
      MGR_CONFIG_FILE: ManagerSettings.json
      AGENT_CONFIG_FILE: AgentSettings.json
      DATA_API_BASE_URL: http://api:5000
      PY_ARTIFACT_PATH: Saltworks.SaltMiner.Python
      PY_CONFIG_FILE: SMv3.json
      DEPLOY_ARTIFACT_PATH: Saltworks.SaltMiner.Deploy
      EXEC_TRANSFORM: true
      DIAGNOSTIC_MODE: ${{ inputs.diagnostic_mode == 'true' && 'true' || 'false' }}
      PUSH_TO_DOCKER_HUB: ${{ inputs.push_to_docker_hub == 'true' && 'true' || 'false' }}

    steps:
    - uses: actions/checkout@v4
    - name: Store artifact paths
      id: paths
      run: |
        echo "sm-artifact-path=Saltworks.SaltMiner.ServiceManager/Saltworks.SaltMiner.ServiceManager/artifacts/bin/Saltworks.SaltMiner.ServiceManager/${{ env.CONFIGURATION}}" >> $GITHUB_OUTPUT
        echo "mgr-dir=Saltworks.SaltMiner.Manager/Saltworks.SaltMiner.Manager" >> $GITHUB_OUTPUT
        echo "mgr-artifact-path=Saltworks.SaltMiner.Manager/Saltworks.SaltMiner.Manager/artifacts/bin/Saltworks.SaltMiner.Manager/${{ env.CONFIGURATION }}" >> $GITHUB_OUTPUT
        echo "agent-dir=Saltworks.SaltMiner.SyncAgent/Saltworks.SaltMiner.SyncAgent" >> $GITHUB_OUTPUT
        echo "agent-artifact-path=Saltworks.SaltMiner.SyncAgent/Saltworks.SaltMiner.SyncAgent/artifacts/bin/Saltworks.SaltMiner.SyncAgent/${{ env.CONFIGURATION }}" >> $GITHUB_OUTPUT

    - name: Use artifacts directory
      run: dotnet new buildprops --use-artifacts
    - name: Restore dependencies
      run: dotnet restore --disable-build-servers
    - name: Build ServiceManager
      run: dotnet build --no-restore --configuration $CONFIGURATION --property WarningLevel=$WARNING_LEVEL

    - name: Show ServiceManager output
      run: |
        ls -lah ${{ steps.paths.outputs.sm-artifact-path }} --group-directories-first
      working-directory: ${{ github.workspace }}
      if: env.DIAGNOSTIC_MODE == 'true'

    # Build Manager
    - name: Set artifacts directory for Manager
      run: dotnet new buildprops --use-artifacts
      working-directory: ${{ github.workspace }}/${{ steps.paths.outputs.mgr-dir }}
    - name: Restore dependencies
      run: dotnet restore --disable-build-servers
      working-directory: ${{ github.workspace }}/${{ steps.paths.outputs.mgr-dir }}
    - name: Build Manager
      run: dotnet build --no-restore --configuration $CONFIGURATION --property WarningLevel=$WARNING_LEVEL
      working-directory: ${{ github.workspace }}/${{ steps.paths.outputs.mgr-dir }}

    - name: Show Manager output
      run: |
        ls -lah ${{ steps.paths.outputs.mgr-artifact-path }} --group-directories-first
      working-directory: ${{ github.workspace }}
      if: env.DIAGNOSTIC_MODE == 'true'

    # Build Agent
    - name: Set artifacts directory for Agent
      run: dotnet new buildprops --use-artifacts
      working-directory: ${{ github.workspace }}/${{ steps.paths.outputs.agent-dir }}
    - name: Restore dependencies
      run: dotnet restore --disable-build-servers
      working-directory: ${{ github.workspace }}/${{ steps.paths.outputs.agent-dir }}
    - name: Build SyncAgent
      run: dotnet build --no-restore --configuration $CONFIGURATION --property WarningLevel=$WARNING_LEVEL
      working-directory: ${{ github.workspace }}/${{ steps.paths.outputs.agent-dir }}

    - name: Show Agent output
      run: |
        ls -lah ${{ steps.paths.outputs.agent-artifact-path }} --group-directories-first
      working-directory: ${{ github.workspace }}
      if: env.DIAGNOSTIC_MODE == 'true'

    # Python
    - name: Determine registry image
      id: registry
      run: |
        if [ "${{ env.PUSH_TO_DOCKER_HUB }}" == "true" ]; then
          echo "image=saltworks/saltminer" >> $GITHUB_OUTPUT
        else
          echo "image=ghcr.io/saltworks/saltminer" >> $GITHUB_OUTPUT
        fi

    - name: Login to GitHub Container Registry
      if: env.PUSH_TO_DOCKER_HUB != 'true'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Login to Docker Hub
      if: env.PUSH_TO_DOCKER_HUB == 'true'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v6
      with:
        images: ${{ steps.registry.outputs.image }}
        tags: |
          type=raw,value=services-${{ github.ref_name }}.${{ github.run_number }}
          type=raw,value=services-${{ github.ref_name }}
        labels: |
          org.opencontainers.image.title=saltminer-services
          org.opencontainers.image.description=SaltMiner Services
          org.opencontainers.image.vendor=Saltworks Security, LLC

    - name: Build and push Docker images
      uses: docker/build-push-action@v6
      with:
        file: .dockerfiles/Dockerfile-services
        context: ${{ github.workspace }}
        push: true
        provenance: mode=max
        sbom: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          ARTIFACT_PATH=${{ steps.paths.outputs.sm-artifact-path }}
          MGR_ARTIFACT_PATH=${{ steps.paths.outputs.mgr-artifact-path }}
          AGENT_ARTIFACT_PATH=${{ steps.paths.outputs.agent-artifact-path }}
          PY_ARTIFACT_PATH=${{ env.PY_ARTIFACT_PATH }}
          JOB_ARTIFACT_PATH=${{ env.DEPLOY_ARTIFACT_PATH }}
      
    - name: Show complete docker tag
      run: echo "${{ steps.meta.outputs.tags }}"
      if: env.DIAGNOSTIC_MODE == 'true'
    
    - name: Extract tag component
      id: extract_tag
      run: echo "tag=`echo '${{ steps.meta.outputs.tags }}' | head -1 | cut -d ':' -f2`" >> $GITHUB_OUTPUT

    - name: Show new tag
      run: echo "Tag ${{ steps.extract_tag.outputs.tag }}"
      if: env.DIAGNOSTIC_MODE == 'true'

    outputs:
      tag: ${{ steps.extract_tag.outputs.tag }}
