name: Saltworks.SaltMiner.DataApi

on:
  push:
    branches:
    - '3.*'
    - "4.*"
    paths:
    - 'Saltworks.SaltMiner.DataApi/**'
    - 'Saltworks.SaltMiner.IndexTemplates/**'
    - '.github/workflows/saltworks-saltminer-dataapi.yml'
    - '.dockerfiles/Dockerfile-api'
  workflow_dispatch:
    inputs:
      push_to_github:
        description: 'Push to GitHub Container Registry'
        required: true
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'
      diagnostic_mode:
        description: 'Enable diagnostic output'
        required: false
        default: false
        type: boolean

env:
  DIAGNOSTIC_MODE: false

jobs:
  build_api:
    name: Build API
    runs-on:
    - self-hosted
    - dotnet
    defaults:
      run:
        working-directory: ./Saltworks.SaltMiner.DataApi/Saltworks.SaltMiner.DataApi
    env:
      CONFIGURATION: release
      CONFIG_FILE: appsettings.json
      KIBANA_BASE_URL: http://kibana:5601
      KESTREL_ALLOW_REMOTE: true
      EXEC_TRANSFORM: true
      DIAGNOSTIC_MODE: ${{ inputs.diagnostic_mode || false }}
      PUSH_TO_GITHUB: ${{ inputs.push_to_github || 'true' }}

    steps:
    - uses: actions/checkout@v4
#    - name: Setup .NET
#      uses: actions/setup-dotnet@v4
#      with:
#        dotnet-version: 8.0.x

    - name: Store artifact path
      run: echo "ARTIFACT_PATH=./artifacts/bin/Saltworks.SaltMiner.DataApi/${{ env.CONFIGURATION}}" >> $GITHUB_ENV
    - name: Calculate Docker-relative paths
      run: |
        echo "DOCKER_ARTIFACT_PATH=Saltworks.SaltMiner.DataApi/Saltworks.SaltMiner.DataApi/artifacts/bin/Saltworks.SaltMiner.DataApi/${{ env.CONFIGURATION}}" >> $GITHUB_ENV
        echo "DOCKER_DATASTORE_SEED_PATH=Saltworks.SaltMiner.IndexTemplates" >> $GITHUB_ENV
    
    - name: Determine registry image
      run: |
        if [ "${{ env.PUSH_TO_GITHUB }}" == "true" ]; then
          echo "REGISTRY_IMAGE=ghcr.io/saltworks/saltminer" >> $GITHUB_ENV
        else
          echo "REGISTRY_IMAGE=saltworks/saltminer" >> $GITHUB_ENV
        fi

    - name: Inspect datastore seed path
      run: |
        ls -lah ${{ github.workspace }}/Saltworks.SaltMiner.IndexTemplates --group-directories-first
      if: env.DIAGNOSTIC_MODE == 'true'

    - name: Use artifacts directory
      run: dotnet new buildprops --use-artifacts
    - name: Restore dependencies
      run: dotnet restore --disable-build-servers
    - name: Build
      run: dotnet build --no-restore --configuration $CONFIGURATION --property WarningLevel=0

    - name: Inspect output
      run: |
        ls -lah ${{ env.ARTIFACT_PATH }} --group-directories-first
      if: env.DIAGNOSTIC_MODE == 'true'

    - name: Login to GitHub Container Registry
      if: env.PUSH_TO_GITHUB == 'true'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Login to Docker Hub
      if: env.PUSH_TO_GITHUB != 'true'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY_IMAGE }}
        tags: |
          type=raw,value=api-${{ github.ref_name }}.${{ github.run_number }}
          type=raw,value=api-${{ github.ref_name }}
        labels: |
          org.opencontainers.image.title=saltminer-api
          org.opencontainers.image.description=SaltMiner API
          org.opencontainers.image.vendor=Saltworks Security, LLC

    - name: Build and push Docker images
      id: push
      uses: docker/build-push-action@v6
      with:
        file: .dockerfiles/Dockerfile-api
        context: ${{ github.workspace }}
        push: true
        provenance: mode=max
        sbom: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          ARTIFACT_PATH=${{ env.DOCKER_ARTIFACT_PATH }}
          DATASTORE_SEED_PATH=${{ env.DOCKER_DATASTORE_SEED_PATH }}

    - name: Show complete docker tag
      run: echo "${{ steps.meta.outputs.tags }}"
      if: env.DIAGNOSTIC_MODE == 'true'
    
    - name: Extract tag component
      run: echo "TAG=`echo '${{ steps.meta.outputs.tags }}' | head -1 | cut -d ':' -f2`" >> $GITHUB_ENV

    - name: Show new tag
      run: echo "Tag ${{ env.TAG }}"
      if: env.DIAGNOSTIC_MODE == 'true'
    
    - id: extract_tag
      run: echo "tag=${{ env.TAG }}" >> $GITHUB_OUTPUT
      name: Set tag output

    outputs:
      tag: ${{ steps.extract_tag.outputs.tag }}

#  update_compose:
#    name: Update Compose
#    runs-on:
#    - self-hosted
#    - dotnet
#    needs: build_api
#    concurrency:
#      group: saltminer-setup-${{ github.ref }}
#      cancel-in-progress: false
#    env:
#      TARGET_KEY: SM_API_IMAGE_VERSION
#
#    steps:
#    - name: Checkout saltminer-setup repo
#      uses: actions/checkout@v4
#      with:
#        repository: saltworks/saltminer-setup
#        token: ${{ secrets.SALTMINER_SETUP }}
#        ref: ${{ github.ref_name }}
#
#    - name: Show current .env file.
#      run: cat .env
#      if: env.DIAGNOSTIC_MODE == 'true'
#
#    - run: sed -i -e "/${{ env.TARGET_KEY }}/ s/=.*$/=${{ needs.build_api.outputs.tag }}/" .env
#      name: Update Compose file  
#
#    - run: cat .env
#      name: Show transformed file.
#      if: env.DIAGNOSTIC_MODE == 'true'
#
#    - name: Push changes
#      run: |
#        git config user.name ${{ github.actor }}
#        git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
#        git add .env
#        git commit -m "Updated .env ${{ env.TARGET_KEY }} value"
#        git push
