name: Saltworks.SaltMiner.JobManager

on:
  push:
    branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]
    paths:
    - 'Saltworks.SaltMiner.JobManager/**'
    - '.github/workflows/saltworks-saltminer-jobmanager.yml'

jobs:
  build_config_wizard:
    name: Saltworks.SaltMiner.JobManager

    runs-on:
    - self-hosted
    - dotnet
    defaults:
      run:
        working-directory: ./Saltworks.SaltMiner.JobManager/Saltworks.SaltMiner.JobManager

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore --disable-build-servers
    - name: Build
      run: dotnet build --no-restore
    #- name: Test
    #  run: dotnet test --no-build --verbosity normal
