name: Saltworks.SaltMiner.JobManager

on:
  push:
    branches: [ "main" ]
    paths:
    - 'Saltworks.SaltMiner.JobManager/**'
    - '.github/workflows/saltworks-saltminer-jobmanager.yml'

env:
  CONFIGURATION: release

jobs:
  build_jobmanager:
    name: Build Saltworks.SaltMiner.JobManager

    runs-on:
    - self-hosted
    - dotnet
    defaults:
      run:
        working-directory: ./Saltworks.SaltMiner.JobManager/Saltworks.SaltMiner.JobManager

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Use artifacts directory
      run: dotnet new buildprops --use-artifacts
    - name: Restore dependencies
      run: dotnet restore --disable-build-servers
    - name: Build
      run: dotnet build --no-restore --configuration $CONFIGURATION

    - name: Store working directory path
      run: echo "WORKING_DIR=$(pwd)" >> $GITHUB_ENV

    - name: Show output
      run: |
        ls -lah ./artifacts/bin/Saltworks.SaltMiner.JobManager/$CONFIGURATION --group-directories-first

    - name: Login to the container registry
      uses: docker/login-action@v3.4.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: saltworks/saltminer
        tags: |
          type=raw,value=jobmanager-${{ github.ref_name }}.{{date 'YYYYMMDD-HHmmss'}}
        labels: |
          org.opencontainers.image.title=saltminer-jobmanager
          org.opencontainers.image.description=SaltMiner JobManager
          org.opencontainers.image.vendor=Saltworks Security, LLC
          org.opencontainers.image.created={{date 'YYYY-MM-DDTHH:mm:ss.SSS[Z]'}}

    - name: Build and push Docker images
      uses: docker/build-push-action@v6.15.0
      with:
        file: .dockerfiles/Dockerfile-jobmanager
        context: ${{ env.WORKING_DIR }}
        push: false
        provenance: mode=max
        sbom: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          ARTIFACT_PATH=./artifacts/bin/Saltworks.SaltMiner.JobManager/${{ env.CONFIGURATION }}
    
    #- name: Test
    #  run: dotnet test --no-build --verbosity normal
