name: Saltworks.SaltMiner.Python (Legacy)

on:
  workflow_dispatch:
  push:
    branches:
    - '3.*'
    paths:
    - 'Saltworks.SaltMiner.Python/**'
    - '.github/workflows/sm25-artifact.yml'

env:
  BRANCH: ${{ github.head_ref || github.ref_name }}

jobs:
  run-python:
    runs-on: self-hosted
    env:
      work-dir: ./Saltworks.SaltMiner.Python
      sln-name: Saltworks.SaltMiner.Python
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate Build Number
        run: |
          RUN_NUMBER=$(printf "%04d" ${{ github.run_number }})
          RUN_ATTEMPT=$(printf "%02d" ${{ github.run_attempt }})
          BUILD_NUMBER="${RUN_NUMBER}-${RUN_ATTEMPT}"
          echo "BUILD_NUMBER=${BUILD_NUMBER}" >> $GITHUB_ENV
  
      - name: Print Build Number
        run: echo "Build Number is $BRANCH.$BUILD_NUMBER"

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Run Python Script
        working-directory: ${{env.work-dir}}
        run: |
          python RunPrunePackage.py . exclusions.json

      - name: What was built?
        run: ls -la ${{env.work-dir}} --group-directories-first
        working-directory: ./

      - name: Upload Unique Artifact
        uses: actions/upload-artifact@v4
        with:
            name: ${{env.sln-name}}.${{env.BRANCH}}.${{env.BUILD_NUMBER}}
            path: ${{env.work-dir}}/*
            retention-days: 10